<?php
// $Id$

/**
 *  @file
 *  Integrating Imageflow with Views jQfx.
 */

 
/**
 *  Implements hook_theme().
 */
function views_jqfx_imageflow_theme($existing, $type, $theme, $path) {
  return array(
    'views_jqfx_imageflow' => array(
      'variables' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'views-jqfx-imageflow',
      'file' => 'views_jqfx_imageflow.theme.inc',
      'path' => $path .'/theme',
    ),
  );
}
