<?php
// $Id$

/**
 *  @file
 *  Integrating Cloud Carousel with Views jQFX.
 */

/**
 * Implements hook_theme().
 */
function views_jqfx_cloud_carousel_theme($existing, $type, $theme, $path) {
  return array(
    'views_jqfx_cloud_carousel' => array(
      'variables' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'views-jqfx-cloud-carousel',
      'file' => 'views_jqfx_cloud_carousel.theme.inc',
      'path' => $path . '/theme',
    ),
  );
}
